version: "3.9"
services:
  my-favorite-star:
    build:
      context: .
    ports:
      - "80:5000"
  mongo:
    image: mongo
    volumes:
      - mongo:/data/db/
    ports:
      - "27017:27017"

volumes:
  mongo: